vim.cmd("set encoding=utf-8")
vim.cmd("set expandtab")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("highlight LineNr guifg=#F6F1DE")
vim.keymap.set("n", "<esc><esc>", ":noh<CR>", { noremap = true, silent = true })
vim.keymap.set("i", "<c-u>", "<c-g>u<c-u>", { noremap = true, silent = true })
vim.keymap.set("i", "<c-w>", "<c-g>u<c-w>", { noremap = true, silent = true })
vim.cmd("set ignorecase smartcase")
